drm: add missing include to fix BSD
src/backend/drm/Renderer.cpp:504:13: error: use of undeclared identifier 'close'
  504 |             close(dupFd);
      |             ^
src/backend/drm/Renderer.cpp:532:13: error: use of undeclared identifier 'close'
  532 |             close(egl.lastBlitSyncFD);
      |             ^