drm: add missing include after 05219d5287df
src/backend/Backend.cpp:317:13: error: use of undeclared identifier 'close'
  317 |             close(newFD);
      |             ^
src/backend/Backend.cpp:323:13: error: use of undeclared identifier 'close'
  323 |             close(newFD);
      |             ^