core: Unbreak build with libc++ (#131)
* backend: remove unused headers after 511600133c64

* backend: add missing header for libc++ after 03677f85616f

src/backend/Backend.cpp:275:42: error: no member named 'find_if' in namespace 'std::ranges'
  275 |     const auto primary    = std::ranges::find_if(implementations, [](SP<IBackendImplementation> value) { return value->type() == Aquamarine::AQ_BACKEND_DRM; });
      |                             ~~~~~~~~~~~~~^