drm: add missing include to fix BSD (#15)
src/backend/Backend.cpp:317:13: error: use of undeclared identifier 'close'
  317 |             close(newFD);
      |             ^
src/backend/Backend.cpp:323:13: error: use of undeclared identifier 'close'
  323 |             close(newFD);
      |             ^